service_name: devops-worker
type: worker
internal: true
container_cpu: 256
container_memory: 512
service_desired_count: 3
healthcheck_path: /ping
dockerfile: Dockerfile
metadata:
  team: devops
  source: golang
environment:
  - name: "PORT"
    value: "8080"
  - name: "DATABASE_HOST"
    value: "localhost"
secret:
  - name: "API_KEY"
    from: "/common/datadog-api-key"
  - name: "API_SECRET"
    from: "/common/datadog-api-key"